---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '>=65.0.0 <66.0.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1h
  targetNamespace: monitoring
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    grafana:
      enabled: true
      admin:
        existingSecret: grafana-admin-credentials
        userKey: admin-user
        passwordKey: admin-password
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - grafana.k8s.lan
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.k8s.lan
      persistence:
        enabled: false

    prometheus:
      enabled: true
      prometheusSpec:
        retention: 7d
        storageSpec: {}
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - prometheus.k8s.lan
        tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus.k8s.lan
    alertmanager:
      enabled: true
      alertmanagerSpec:
        storage: {}
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - alertmanager.k8s.lan
        tls:
          - secretName: alertmanager-tls
            hosts:
              - alertmanager.k8s.lan
    nodeExporter:
      enabled: true

    kubeStateMetrics:
      enabled: true

    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeEtcd:
      enabled: false
