---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    AUTH_KEY: AgA_REPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: tailscale-auth
      namespace: tailscale
    type: Opaque
